version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - apt-get update -y -q
      - apt-get install -y clang cmake ninja-build libgtk-3-dev
      - echo Installing Flutter...
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter config --no-analytics
      - flutter doctor
      - flutter config --enable-web --no-enable-android --no-enable-ios

  pre_build:
    commands:
      - cd registration
      - flutter pub get
      - dart fix --apply
      - dart analyze

  build:
    commands:
      - echo Building web application...
      - flutter build web --release --dart-define=USER_POOL_ID=$USER_POOL_ID --dart-define=CLIENT_ID=$CLIENT_ID --target=main.dart

  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 cp build/web s3://$S3_BUCKET_NAME/ --recursive

artifacts:
  base-directory: registration/build/web
  files:
    - "**/*"
