---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  UserPoolName:
    Type: String
    Description: Name of the user pool
    Default: my-user-pool
  AppClientName:
    Type: String
    Description: Name of the app client
    Default: my-app-client
  CallbackURL:
    Type: String
    Description: URL of the callback for the app client
    Default: https://localhost:3000/callback
  SignOutURL:
    Type: String
    Description: URL of the sign-out page for the app client
    Default: https://localhost:3000/sign-out
  ReplyEmailAddress:
    Type: String
    Description: Email address to send from
  VerificationSubject:
    Type: String
    Description: Subject of the email verification message
    Default: Your verification link

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
        ReplyToEmailAddress: !Ref ReplyEmailAddress
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        InviteMessageTemplate:
          EmailMessage: 'Your username is {username} and temporary password is {####}.'
          EmailSubject: 'Your temporary password'
          SMSMessage: 'Your username is {username} and temporary password is {####}.'
        UnusedAccountValidityDays: 7
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Name: given_name
          Required: false
        - AttributeDataType: String
          Name: family_name
          Required: false
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationSubject: !Ref VerificationSubject
      EmailVerificationMessage: 'Please click the link below to verify your email address. {####}'

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Ref AppClientName
      GenerateSecret: true
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Ref CallbackURL
      LogoutURLs:
        - !Ref SignOutURL
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Ref UserPoolName

  CognitoReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy providing read-only access to Cognito user objects"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - cognito-idp:ListUsers
              - cognito-idp:DescribeUserPool
            Resource: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}"

  CognitoReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CognitoReadOnlyPolicy
      Description: "Role with read-only access to Cognito user objects"

Outputs:
  UserPoolId:
    Description: The ID of the user pool
    Value: !Ref CognitoUserPool
  UserPoolArn:
    Description: The ARN of the user pool
    Value: !GetAtt CognitoUserPool.Arn
  UserPoolClientId:
    Description: The ID of the user pool client
    Value: !Ref CognitoUserPoolClient
  UserPoolClientSecret:
    Description: The secret of the user pool client
    Value: !GetAtt CognitoUserPoolClient.ClientSecret
  UserPoolDomain:
    Description: The domain of the user pool
    Value: !Ref CognitoUserPoolDomain