name: Cloud formation Analysis

on:
  push:
    branches: [develop, qa, prod]
    paths:
      - "cf/*.yml"
  pull_request:
    paths:
      - "cf/*.yml"

permissions:
  contents: read

jobs:
  evaluate-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Analysis Tools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cfn-lint
      - name: Validate CloudFormation Templates
        run: |
          cfn-lint ./cf/*.yml
